apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: main

resources:
  - namespace.yaml
  - ../../_source/apps/app2
  - ../../_source/apps/app3

helmGlobals:
  chartHome: ../../_source/apps

helmCharts:
  - name: app1
    releaseName: app1
    valuesFile: app1-values.yaml
    namespace: main

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: app2-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: app2.chetan.com
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: app3-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: app3.chetan.com

labels:
  - includeSelectors: false
    pairs:
      environment: production
      branch: main
